version: 2.1

jobs:
  build-and-test:
    docker:
      - image: florianmgs/oc_p13_lettings
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: source venv/bin/activate && pip install -r requirements.txt
      - run: source venv/bin/activate && flake8
      - run: source venv/bin/activate && pytest

workflows:
  main:
    jobs:
      - build-and-test