version: 2.1
orbs:
  python: circleci/python@1.1.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            pytest
            flake8
          name: Test
workflows:
  main:
    jobs:
      - build